//go:build !ignore_autogenerated

/*
Copyright 2026.
Project: hpatuner
Author: Md. Abul Kalam Musa
Licensed under the Apache License, Version 2.0 (the "License");
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HpaTuner) DeepCopyInto(out *HpaTuner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HpaTuner.
func (in *HpaTuner) DeepCopy() *HpaTuner {
	if in == nil {
		return nil
	}
	out := new(HpaTuner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HpaTuner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HpaTunerList) DeepCopyInto(out *HpaTunerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HpaTuner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HpaTunerList.
func (in *HpaTunerList) DeepCopy() *HpaTunerList {
	if in == nil {
		return nil
	}
	out := new(HpaTunerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HpaTunerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HpaTunerSpec) DeepCopyInto(out *HpaTunerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HpaTunerSpec.
func (in *HpaTunerSpec) DeepCopy() *HpaTunerSpec {
	if in == nil {
		return nil
	}
	out := new(HpaTunerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HpaTunerStatus) DeepCopyInto(out *HpaTunerStatus) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HpaTunerStatus.
func (in *HpaTunerStatus) DeepCopy() *HpaTunerStatus {
	if in == nil {
		return nil
	}
	out := new(HpaTunerStatus)
	in.DeepCopyInto(out)
	return out
}
